/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MiEstanciaRouteImport } from './routes/mi-estancia'
import { Route as VillaAzaharRouteImport } from './routes/villa-azahar'
import { Route as VillaPonienteRouteImport } from './routes/villa-poniente'
import { Route as VillaSalobreRouteImport } from './routes/villa-salobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEstanciaRoute = MiEstanciaRouteImport.update({
  id: '/mi-estancia',
  path: '/mi-estancia',
  getParentRoute: () => rootRouteImport,
} as any)
const VillaAzaharRoute = VillaAzaharRouteImport.update({
  id: '/villa-azahar',
  path: '/villa-azahar',
  getParentRoute: () => rootRouteImport,
} as any)
const VillaPonienteRoute = VillaPonienteRouteImport.update({
  id: '/villa-poniente',
  path: '/villa-poniente',
  getParentRoute: () => rootRouteImport,
} as any)
const VillaSalobreRoute = VillaSalobreRouteImport.update({
  id: '/villa-salobre',
  path: '/villa-salobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-estancia': typeof MiEstanciaRoute
  '/villa-azahar': typeof VillaAzaharRoute
  '/villa-poniente': typeof VillaPonienteRoute
  '/villa-salobre': typeof VillaSalobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-estancia': typeof MiEstanciaRoute
  '/villa-azahar': typeof VillaAzaharRoute
  '/villa-poniente': typeof VillaPonienteRoute
  '/villa-salobre': typeof VillaSalobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mi-estancia': typeof MiEstanciaRoute
  '/villa-azahar': typeof VillaAzaharRoute
  '/villa-poniente': typeof VillaPonienteRoute
  '/villa-salobre': typeof VillaSalobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mi-estancia'
    | '/villa-azahar'
    | '/villa-poniente'
    | '/villa-salobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mi-estancia'
    | '/villa-azahar'
    | '/villa-poniente'
    | '/villa-salobre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mi-estancia'
    | '/villa-azahar'
    | '/villa-poniente'
    | '/villa-salobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MiEstanciaRoute: typeof MiEstanciaRoute
  VillaAzaharRoute: typeof VillaAzaharRoute
  VillaPonienteRoute: typeof VillaPonienteRoute
  VillaSalobreRoute: typeof VillaSalobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-estancia': {
      id: '/mi-estancia'
      path: '/mi-estancia'
      fullPath: '/mi-estancia'
      preLoaderRoute: typeof MiEstanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villa-azahar': {
      id: '/villa-azahar'
      path: '/villa-azahar'
      fullPath: '/villa-azahar'
      preLoaderRoute: typeof VillaAzaharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villa-poniente': {
      id: '/villa-poniente'
      path: '/villa-poniente'
      fullPath: '/villa-poniente'
      preLoaderRoute: typeof VillaPonienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villa-salobre': {
      id: '/villa-salobre'
      path: '/villa-salobre'
      fullPath: '/villa-salobre'
      preLoaderRoute: typeof VillaSalobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MiEstanciaRoute: MiEstanciaRoute,
  VillaAzaharRoute: VillaAzaharRoute,
  VillaPonienteRoute: VillaPonienteRoute,
  VillaSalobreRoute: VillaSalobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
